# Generated by Django 4.2.3 on 2023-08-28 20:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_remove_user_followers_remove_user_following_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='users_mg_this_post',
            field=models.ManyToManyField(blank=True, related_name='users_mg_this_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
