# Generated by Django 4.2.3 on 2023-09-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0015_remove_post_id_user_remove_post_users_mg_this_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='categoria',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='dni',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='enfermedades',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='user',
            name='fecha_nacimiento',
            field=models.DateField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='genero',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='lesiones',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='user',
            name='mail_verificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='posicion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telefono1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telefono2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='trayectoria',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
