# Generated by Django 4.2.3 on 2023-09-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0016_user_categoria_user_dni_user_enfermedades_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='logeado_como',
            field=models.CharField(default='jugador', max_length=100),
        ),
    ]
