# Generated by Django 4.2.3 on 2023-09-03 08:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0017_user_logeado_como'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='categoria_estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='categoria',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cebollitas', models.ManyToManyField(blank=True, related_name='cebollitas', to=settings.AUTH_USER_MODEL)),
                ('cuarta', models.ManyToManyField(blank=True, related_name='categorias_cuarta', to=settings.AUTH_USER_MODEL)),
                ('decima', models.ManyToManyField(blank=True, related_name='categorias_decima', to=settings.AUTH_USER_MODEL)),
                ('doceava', models.ManyToManyField(blank=True, related_name='categorias_doceava', to=settings.AUTH_USER_MODEL)),
                ('novena', models.ManyToManyField(blank=True, related_name='categorias_novena', to=settings.AUTH_USER_MODEL)),
                ('octava', models.ManyToManyField(blank=True, related_name='categorias_octava', to=settings.AUTH_USER_MODEL)),
                ('quinta', models.ManyToManyField(blank=True, related_name='categorias_quinta', to=settings.AUTH_USER_MODEL)),
                ('septima', models.ManyToManyField(blank=True, related_name='categorias_septima', to=settings.AUTH_USER_MODEL)),
                ('sexta', models.ManyToManyField(blank=True, related_name='categorias_sexta', to=settings.AUTH_USER_MODEL)),
                ('undecima', models.ManyToManyField(blank=True, related_name='categorias_undecima', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
