# Generated by Django 4.2.3 on 2023-09-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0018_user_categoria_estado_alter_user_categoria_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
