# Generated by Django 4.2.3 on 2023-09-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0019_alter_user_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
