# Generated by Django 4.2.3 on 2023-09-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0020_categoria_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='cebollitas',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='cuarta',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='decima',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='doceava',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='novena',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='octava',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='quinta',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='septima',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='sexta',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='undecima',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
