# Generated by Django 4.2.3 on 2023-09-04 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0022_asistencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='tipo_asistencia',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
