# Generated by Django 4.2.3 on 2023-09-04 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0023_alter_asistencia_tipo_asistencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='tipo_asistencia',
        ),
    ]
