# Generated by Django 4.2.3 on 2023-09-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0024_remove_asistencia_tipo_asistencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
