# Generated by Django 4.2.3 on 2023-09-04 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0025_alter_asistencia_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='categoria',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='asistencias_categoria', to='network.categoria'),
        ),
    ]
