# Generated by Django 4.2.3 on 2023-09-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0027_alter_asistencia_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='categoria',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
