# Generated by Django 4.2.3 on 2023-09-04 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0030_asistencia_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='editada_por',
            field=models.ForeignKey(blank=True, default=False, on_delete=django.db.models.deletion.CASCADE, related_name='asistencias_editada_por', to=settings.AUTH_USER_MODEL),
        ),
    ]
