# Generated by Django 4.2.3 on 2023-09-04 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0031_asistencia_editada_por'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='editada_por',
        ),
    ]
