# Generated by Django 4.2.3 on 2023-09-05 19:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0032_remove_asistencia_editada_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='usuarios_en_categoria',
            field=models.ManyToManyField(blank=True, related_name='usuarios_en_categoria', to=settings.AUTH_USER_MODEL),
        ),
    ]
