# Generated by Django 4.2.3 on 2023-09-07 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0034_alter_user_posicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='convocado_estado',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rival', models.CharField(max_length=50)),
                ('condicion', models.CharField(max_length=50)),
                ('hora_comienzo', models.DateTimeField()),
                ('hora_citacion', models.DateTimeField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partido_categoria', to='network.categoria')),
                ('usuarios', models.ManyToManyField(blank=True, related_name='usuarios_convocados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
