# Generated by Django 4.2.3 on 2023-09-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0036_partido_partido_finalizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='formacion',
            field=models.JSONField(default=list),
        ),
    ]
