# Generated by Django 4.2.3 on 2023-09-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0037_partido_formacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='goles_jugador',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ta_jugador',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tr_jugador',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
