# Generated by Django 4.2.3 on 2023-09-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0038_user_goles_jugador_user_ta_jugador_user_tr_jugador'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='suplente',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='titular',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
