# Generated by Django 4.2.3 on 2023-09-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0039_user_suplente_user_titular'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='comentario',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='partido',
            name='gc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partido',
            name='gf',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partido',
            name='resultado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
