# Generated by Django 4.2.3 on 2023-09-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0042_alter_user_suplente_alter_user_titular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='gc',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='partido',
            name='gf',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='goles_jugador',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='ta_jugador',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='tr_jugador',
            field=models.IntegerField(default=0),
        ),
    ]
